language: node_js
node_js:
  - "12"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${{ secrets.GITHUB_TOKEN }}
  local_dir: build
  on:
    branch: master
